name: Requests Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target_url:
        description: 'The URL to send the GET request to'
        required: false
        default: 'https://www.google.com'

jobs:
  requests_test_job:
    runs-on: ubuntu-latest

    env:
      TARGET_URL: ${{ github.event.inputs.target_url || 'https://www.google.com' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Print environment variable and secret
        run: |
          echo "Secret from GitHub: ${{ secrets.MY_SECRET }}"
          echo "Target URL: $TARGET_URL"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run request script
        run: |
          python request_script.py
