name: Example Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target_url:
        description: 'The URL to send the GET request to'
        required: true
        default: 'https://www.google.com'

jobs:
  example_job:
    runs-on: ubuntu-latest

    env:
      GLOBAL_VAR: 'This is a global environment variable'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Print environment variable and secret
        run: |
          echo "Global environment variable: $GLOBAL_VAR"
          echo "Secret from GitHub: ${{ secrets.MY_SECRET }}"
          echo "Target URL: ${{ github.event.inputs.target_url }}"

      - name: Install dependencies
        run: |
          pip install requests
      
      - name: Run request script
        env:
          TARGET_URL: ${{ github.event.inputs.target_url }}
        run: |
          python request_script.py
